### ISSUE TITLE
Any chance for a merge from a fork and release to clojars?

### ISSUE THREAD

**Issue by robert-stuttaford** [vlacs/saml20-clj#3]
Hi all, 

This fork https://github.com/sgsfak/saml20-clj by @sgsfak appears to be quite a bit more capable than what's in this repo.

Is there a chance, @sgsfak, that you could PR your changes for @moquist or @jrdoane to merge, and then for either one of those chaps to push a new version release to clojars?

Otherwise I'd fork sgsfak's and put a different jar on clojars entirely, which is sub-optimal for the community at large.

I'd be happy to do all this myself on your respective behalfs, had I the requiste permissions to do so.

Thanks for any help you can provide!

**Comment by sgsfak** [comment]
Hi, I have just created a pull request (#4) with my changes. This version "works for me" but it may need to be tested in other scenarios and environments. Also I don't like the fact that I introduced dependencies to [apache santuario](https://santuario.apache.org/) and [opensaml](https://wiki.shibboleth.net/confluence/display/OpenSAML/Home/) but it appeared to be the quicker solution for supporting xml signatures and enryption/decryption...

**Comment by robert-stuttaford** [comment]
Thank you, @sgsfak. Let's see what the others say.

**Comment by jrdoane** [comment]
@sgsfak Sorry I didn't getback to you sooner. This was one of my first Clojure projects so it's not exactly designed the way I would have liked. I've merged the pull request and I've gone through and ensured that the library still functions even without a keystore to handle encrypted (and decrypting,) assertions as the SSO part of the SAML spec doesn't require this functionality. I updated /dev/user.clj and /dev/web.clj since they were broken from the changes in the pull request. It also now offers two route formats: Clojars and Helmsman. I'm also now initializing OpenSAML earlier when the factory function is created since OpenSAML can still be used even if we're not decrypting assertions in certain instances (bootstrapping was running when the decrypter was made, which doesn't happen without a keystore now.)

I also noticed that the data you were getting from the SAML Assertions wasn't including a Name ID or Name ID Format which are required for knowing who just SSO'ed into your system, so I added it.

A secondary note, I noticed that the code you wrote can parse several SAML assertions but, IIRC, an SSO request will only ever have one assertion with one subject, with one name ID. I'm leaving it the way it is now but, I don't see much point in support multiple assertions for SSO unless I missed something in the spec.

Lastly, I noticed that there were changes to how the saml20-config was going to look, so I updated the config-dist.edn to reflect that new structure.

I made your changes work with what I needed, bumped the version, and released `0.1.5` to Clojars. I also updated dependencies so there were fewer conflicts between libraries.

I'm using this in a project now so, you may see updates to this library as I need them. If you have questions, just holler. I do plan on cleaning up this library at some point in the future so functionality is split apart a bit more than it was the first time around.
