### ISSUE TITLE
working example #2

### ISSUE THREAD

**Issue by altV** [vlacs/saml20-clj#5]
hello,

I'm having a problem with working example - not sure about non-working sr/saml-routes, specifically, empty GET /saml endpoint

**Comment by altV** [comment]
ok, the real demo is the two other files, "web" and "user". and also you have to use helmsman now, not the saml-routes that documented

**Comment by jrdoane** [comment]
There are two examples, the example that uses Compojure was done by another person and it resides at `dev/dev/demo_sp.clj` if that's helpful at all. I'm not sure how functional it is since I simply pulled it in from a pull request done by @sgsfak. I did end up making a handful of changes that I don't think should have impacted that example from working but I needed (such as not requiring the SP to encrypt assertions.)

Also, the saml-routes weren't removed. They were added by @sgsfak and they can be found in `src/saml20_clj/routes.clj` The example file I mentioned above uses this I believe.
